columnList = [
    "hour",
    "dayOfTheWeek",
    "timeWindow",
    "isWeekend",
    "isNight",
    "srcIp",
    "dstIp",
    "sourcePort",
    "destinationPort",
    "totalLength",
    "tcpFlags",
    "protocol",
    "ttl",
]

choseColumns = [
    "isWeekend",
    "isNight",
    "srcIp",
    "connCount",
    "uniqueDstIps",
    "uniqueSrcPorts",
    "uniqueDstPorts",
    "commonDstPort",
    "avgPacketSize",
    "stdPacketSize",
    "totalBytes",
    "synCount",
    "mainProtocol",
    "avgTtl",
    "stdTtl",
    "synRatio",
    "dstIpEntropy",
    "portEntropy",
    "bytesPerConn",
]
